noinst_PROGRAMS = \
	test-bcon

TEST_PROGS = \
	test-bcon

AM_CPPFLAGS = \
	-Ibcon \
	$(BSON_CFLAGS)

test_bcon_SOURCES = tests/test-bcon.c
test_bcon_LDADD = libbcon.la

test: $(TEST_PROGS)
	@ for TEST_PROG in $(TEST_PROGS) ; do \
		libtool --mode=execute $$VALGRIND ./$$TEST_PROG ; \
	done
