noinst_PROGRAMS = \
	test-bcon

TESTS = test-bcon

check_PROGRAMS = \
	test-bcon

AM_CPPFLAGS = \
	-Ibcon \
	$(CHECK_CFLAGS) \
	$(BSON_CFLAGS)

test_bcon_SOURCES = tests/test-bcon.c
test_bcon_LDADD = libbcon.la $(CHECK_LIBS)

